const productData = [
  {
    id: 1,
    name: "iQOO Neo 6 5G",
    imageURL: "p1",
    price: "399",
    category: "Phone",
    brand: "iQOO",
    desc: "iQOO Neo 6 5G is a robust performer, housing 8GB RAM backed by a Flash Charging enabled battery panel and 128GB internal space. Its front and back camera profiles are also quite explicit, providing access to detailed captures on the go.",
  },
  {
    id: 2,
    name: "Google Pixel 6A",
    imageURL: "p2",
    price: "349",
    category: "Phone",
    brand: "Google",
    desc: "Get yourself a Google Pixel 6A to binge-watch on favourite shows, capture moments as they are and store all those extra media files which might look unnecessary to many but means a lot to you. Also, a 4410mAh 18W Fast Charging equipped battery loaded within gets you throughout the day on a single charge.   ",
  },
  {
    id: 3,
    name: "iPhone 14 Pro Max",
    imageURL: "p3",
    price: "899",
    category: "Phone",
    brand: "Apple",
    desc: "The iPhone 14 Pro Max is the latest addition to the entire series, enabling access to seamless visuals, impressive internal storage and detailed snaps. However, the particular variant is void of a fingerprint sensor and FM Radio. ",
  },
  {
    id: 4,
    name: "Galaxy S22 Ultra",
    imageURL: "p4",
    price: "699",
    category: "Phone",
    brand: "Samsung",
    desc: "The Galaxy S22 Ultra is yet another flagship performer from Samsung, offering a variety of promising specs. Its massive internal storage, 12GB RAM, great cameras and a powerful battery lets you enjoy seamless operations throughout the day. Moreover, Samsung has also incorporated an on-screen fingerprint sensor within. ",
  },
  {
    id: 5,
    name: "Redmi Note 12 Pro 5G",
    imageURL: "p5",
    price: "499",
    category: "Phone",
    brand: "Xiaomi",
    desc: "Xiaomi Redmi Note 12 Pro 5G presents a perfect blend of power and consistency. A 5000mAh battery enables users to continue with their operations for prolonged hours whereas its 128GB internal storage can be used to save plenty of apps and files. The brand has also provided a fingerprint sensor on the side, making it more convenient to use. ",
  },
  {
    id: 6,
    name: "ROG Phone 6",
    imageURL: "p6",
    price: "699",
    category: "Phone",
    brand: "Asus",
    desc: "Asus ROG Phone 6, like its predecessors, turns out to be a powerful flagship investment, assuring a premium operative experience. The brand has placed a robust battery configuration within, enabling prolonged usage hours. For those who are looking for great cameras, a robust processor setup and stunning visuals, the particular gadget is an ideal match.   ",
  },
  {
    id: 7,
    name: "White Hoodie",
    imageURL: "p7",
    price: "69",
    category: "Fashion",
    brand: "Adidas",
    desc: "This hoodie from adidas Basketball is made of cotton and polyester doubleknit fabric for warmth and comfort that's soft to the touch. Ribbing on the cuffs and hem lock you in while badges on the front, back and sleeves provide a signature finish.",
  },
  {
    id: 8,
    name: "Fresh Foam X Hierro v7",
    imageURL: "p8",
    price: "139",
    category: "Fashion",
    brand: "New Balance",
    desc: "People love the idea of adventure in the great outdoors, but theres more to the natural landscape than fresh air and scenic views. Uneven terrain, debris, and moisture are unique challenges to footwear that require specialized construction. ",
  },
  {
    id: 9,
    name: "NB Heat Grid Half Zip",
    imageURL: "p9",
    price: "89",
    category: "Fashion",
    brand: "New Balance",
    desc: "Our NB Heat Grid Half Zip is built for cold-weather runs with NB HEAT technology to help you feel warm while wicking away moisture so you can stay focused on your performance. ",
  },
  {
    id: 10,
    name: "Xiaomi Smart TV 5A",
    imageURL: "p10",
    price: "300",
    category: "Electronics",
    brand: "Xiaomi",
    desc: "Xiaomi Smart TV 5A 40 inch (101 cm) LED Full HD TV price in US starts from us 300. The lowest price of Xiaomi Smart TV 5A 40 inch (101 cm) LED Full HD TV is USD 300 at croma.com. This is 1.5 GB RAM / 8 GB internal storage base variant of Xiaomi Smart TV 5A 40 inch (101 cm) LED Full HD TV which is available in Black,gold colour.",
  },
  {
    id: 11,
    name: "Samsung 80 cm (32 inch) HD Ready",
    imageURL: "p11",
    price: "200",
    category: "Electronics",
    brand: "Samsung",
    desc: "Enjoy HD TV in Digital era. Once you see high definition of TV with vivid and crisp details, you’ll never look back to standard definition or analog TVs.",
  },
  {
    id: 12,
    name: "Realme 139 cm (55 inch) Ultra HD",
    imageURL: "p12",
    price: "600",
    category: "Electronics",
    brand: "Realme",
    desc: "The realme Smart TV features a Premium Bezel-less design with bezels as thin as 8.7mm. This is the immersive smart cinema experience your living room needs.",
  },
  {
    id: 13,
    name: "Asus TUF Gaming FX506HCB",
    imageURL: "p13",
    price: "699",
    category: "Laptop",
    brand: "Asus",
    desc: "ASUS TUF Gaming F15 Core i7 11th Gen - (16 GB/1 TB SSD/Windows 10 Home/4 GB Graphics/NVIDIA GeForce RTX 3050/144 Hz) FX506HCB-HN225T Gaming Laptop(15.6 inch, Graphite Black, 2.30 kg)",
  },
  {
    id: 14,
    name: "MacBook Air M1",
    imageURL: "p14",
    price: "599",
    category: "Laptop",
    brand: "Apple",
    desc: "Apple MacBook Air 2020 (M1, 13.3 Inch, 8GB, 256GB, macOS Big Sur,silver)",
  },
  {
    id: 15,
    name: "MSI GF63 Thin 10SCXR",
    imageURL: "p15",
    price: "599",
    category: "Laptop",
    brand: "MSI",
    desc: "MSI GF63 Thin 10SCXR-1617IN Laptop (Core i7 10th Gen/8 GB/1 TB 256 GB SSD/Windows 10/4 GB) Specifications",
  },
];
